server:
  port: 8010

elements:
  - id: "btn_1"
    type: "button"
    label: "Button"

  - id: "chk_agreed"
    type: "checkbox"
    label: "Checkbox"

  - id: "txt_username"
    type: "textbox"
    label: "Text Box"
