server:
  port: 5500

elements:
  - id: "btn_1"
    type: "button"
    label: "Submit Request"
  
  - id: "btn_2"
    type: "button"
    label: "Cancel"

  - id: "chk_agreed"
    type: "checkbox"
    label: "I agree to terms"

  - id: "txt_username"
    type: "textbox"
    label: "Username"

  - id: "btn_fast"
    type: "button"
    label: "Fast Click"
