server:
  port: 8010

elements:
  - id: "button"
    type: "button"
    label: "Button"

  - id: "checkbox"
    type: "checkbox"
    label: "Checkbox"

  - id: "textbox"
    type: "textbox"
    label: "Text Box"
